//
// Created by Manuel Jesús Romero Mateos on 18/11/21.
//

#ifndef INC_2021_EEDD_PRACTICAS_TARJETAVACUNACION_H
#define INC_2021_EEDD_PRACTICAS_TARJETAVACUNACION_H


class TarjetaVacunacion {

};


#endif //INC_2021_EEDD_PRACTICAS_TARJETAVACUNACION_H
